In [1]:
import numpy as np

In [3]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
#Return evenly spaced values within a given interval
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Generate arrays of zeros or ones
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#Return evenly spaced numbers over a specified interval
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
#Creates an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#Numpy also has lots of ways to create random number arrays:
np.random.rand(2)

array([0.54618927, 0.62496032])

In [20]:
np.random.rand(5,4)

array([[0.94760673, 0.8829503 , 0.78552017, 0.00237119],
       [0.24190049, 0.23567354, 0.92735087, 0.79010614],
       [0.14160492, 0.93798585, 0.16217548, 0.84656882],
       [0.94305145, 0.63209261, 0.1070665 , 0.48171372],
       [0.54104333, 0.09167287, 0.2602855 , 0.17095102]])

In [21]:
#randn:Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform
np.random.randn(2)

array([ 0.52670447, -0.33795154])

In [22]:
np.random.randn(5,4)

array([[ 0.71339125,  1.35257409, -0.15615632,  0.25329866],
       [ 0.82713356,  1.20599425,  0.41646239, -1.1162933 ],
       [ 1.07199015, -0.7895903 , -0.58736946, -0.51374264],
       [ 0.94508538,  0.12847396,  0.0597375 , -0.39534706],
       [-2.7091417 , -0.81294767, -0.44828418,  0.06649829]])

In [23]:
#randomint
np.random.randint(1,100)

75

In [24]:
np.random.randint(1,100,10)

array([80, 69, 58, 24, 92, 45, 11, 90, 11, 55])

In [26]:
#Array Attributes and Methods
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)
ranarr

array([48, 31, 16,  3,  1, 19, 16, 48,  9,  4])

In [32]:
#Reshape
arr2 = np.arange(24)
arr2
arr2.reshape(2, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [37]:
#max,min,argmax,argmin
ranarr2 = np.random.randint(0, 10, 8)
ranarr2

array([1, 5, 4, 7, 6, 9, 2, 1])

In [38]:
ranarr2.max()

9

In [39]:
ranarr2.argmax() #gives index position of 9

5

In [42]:
ranarr2.min()

1

In [43]:
ranarr2.argmin()

0

In [57]:
#Shape is an attribute that arrays have (not a method)
#Vector
arr3 = np.arange(0, 3)
arr3
arr3.shape

(3,)

In [58]:
#You can also grab the data type of the object in the array
arr3.dtype

dtype('int64')