In [1]:
import numpy as np

In [3]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Get a value at an index
arr[8]

8

In [6]:
#Get values in a range
arr[2:5]

array([2, 3, 4])

In [7]:
#BROADCASTING
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Reset array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
#Now note the changes also occur in our original array!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
#Data is not copied, it's a view of the original array! This avoids memory problems!
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
#Indexing a 2D array (matrices)
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [16]:
# Getting individual element value
arr_2d[1][0]

20

In [28]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:3,:1]

array([[ 5],
       [20],
       [35]])

In [30]:
#Fancy Indexing
#Fancy indexing allows you to select entire rows or columns out of order,to show this,
#let's quickly build out a numpy array
arr2dz = np.zeros((10,10))
arr2dz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
arr_length = arr2dz.shape[1]
arr_length

10

In [37]:
for i in range(arr_length):
    arr2dz[i] = i + 1
    
arr2dz

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [39]:
arr2dz[[1,3,5,7]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [40]:
#Allows in any order
arr2dz[[6,4,2,7]]

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [41]:
#Selection
selarr = np.arange(1,11)
selarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
selarr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bolarr = selarr > 4
bolarr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
selarr[bolarr]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
selarr[selarr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])